# Generated by Django 5.0.1 on 2024-01-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CS', 'Cut Shapes'), ('NS', 'Natural Shapes')], default='CS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Charging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Charging Date')),
                ('method', models.CharField(choices=[('FM', 'Full Moon'), ('SL', 'Sun Light'), ('So', 'Sound'), ('Se', 'Selenite'), ('Sm', 'Smudge'), ('Wa', 'Water')], default='FM', max_length=100)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crystal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crystal')),
            ],
        ),
        migrations.AddField(
            model_name='crystal',
            name='shapes',
            field=models.ManyToManyField(to='main_app.shape'),
        ),
    ]
