# Generated by Django 5.0.1 on 2024-01-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shape_charging_photo_crystal_shapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('CS', 'Cut Shapes'), ('NS', 'Natural Shapes')], max_length=100),
        ),
    ]
