# Generated by Django 5.0.1 on 2024-01-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_shape_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='type',
        ),
        migrations.AddField(
            model_name='shape',
            name='formation',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Cut', 'Cut')], default='Natural', max_length=100),
        ),
    ]
